# Generated by Django 4.1.5 on 2023-01-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=500)),
                ('ars', models.CharField(max_length=100)),
                ('acrs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='R1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('l', models.CharField(max_length=500)),
                ('w', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('q', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='R2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('l', models.CharField(max_length=500)),
                ('w', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('q', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadid', models.CharField(max_length=150)),
                ('rname', models.CharField(max_length=400)),
                ('ars', models.CharField(max_length=100)),
                ('acrs', models.CharField(max_length=100)),
            ],
        ),
    ]
