# Generated by Django 4.1.5 on 2023-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcostsummary',
            name='roadid',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
