# Generated by Django 4.1.5 on 2023-01-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0002_alter_roadcostsummary_roadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcostsummary',
            name='roadid',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
