# Generated by Django 4.1.5 on 2023-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0003_alter_roadcostsummary_roadid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=10)),
                ('no', models.CharField(max_length=10)),
                ('q', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='R1_1',
        ),
        migrations.DeleteModel(
            name='R2_1',
        ),
    ]
