# Generated by Django 4.1.5 on 2023-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0005_alter_boq_amount_alter_boq_desc_alter_boq_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcostsummary',
            name='roadid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
