# Generated by Django 4.1.5 on 2023-01-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0006_alter_roadcostsummary_roadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='q',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='rate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
