# Generated by Django 4.1.5 on 2023-01-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0007_alter_boq_no_alter_boq_q_alter_boq_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
