# Generated by Django 4.1.5 on 2023-01-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0008_alter_boq_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='R1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True)),
                ('l', models.CharField(blank=True, max_length=500, null=True)),
                ('w', models.CharField(blank=True, max_length=500, null=True)),
                ('d', models.CharField(blank=True, max_length=500, null=True)),
                ('q', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
