# Generated by Django 4.1.5 on 2023-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0009_r1_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r1_1',
            name='d',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='l',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='q',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='w',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
