# Generated by Django 4.1.5 on 2023-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0010_alter_r1_1_d_alter_r1_1_l_alter_r1_1_no_alter_r1_1_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r1_1',
            name='d',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='l',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='no',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='r1_1',
            name='w',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
